<?php $_code = $this->getMethodCode(); ?>
<fieldset>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none;">
        <li>
            <div id="mundipagg_boleto">
                <ul >
                    <li style="clear:both">
                        <div class="input-box">
                            <label>CPF ou CNPJ<span class="required">*</span></label><br/>
                            <input type="text" id="<?php echo $_code ?>_boleto_taxvat" name="payment[boleto_taxvat]" />
                        </div>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</fieldset>
