<?php $_code=$this->getMethodCode() ?>
<?php
$status = $this->getInstallmentsStatus();
?>
<fieldset>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" class="input-text required-entry" title="<?php echo $this->__('Credit Card Number') ?>" pattern="\d*" maxlength="19" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" autocomplete="off" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div>
                <select id="<?php echo $_code ?>_expiration" class="month">
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div>
                <span>/</span>
                <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry" autocomplete="off">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
</ul>
</fieldset>